name: Release - crate

env:
  PIPELINE: test
  RELEASE_TARGET: x86_64-unknown-linux-gnu

on:
  push:
    tags:
      - 'release/**'
# FIXME: remove after testing done
    branches:
      - chore-add-ci

jobs:
  test-release:
    uses: ./.github/workflows/test.yml
  push-crates:
    runs-on: ubuntu-latest
    needs:
      - test-release
    steps:
      - name: checkout this source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: push crates to registry
        uses: katyo/publish-crates@v2
        with:
          registry-token: "test" #${{ secrets.CARGO_REGISTRY_TOKEN }}
          args: --dry-run
  make_github_release:
    runs-on: ubuntu-latest
    if: ${{ success() && github.ref_type == 'tag' }}
    needs:
      - push-crates
    permissions:
      contents: write
    steps:
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          generateReleaseNotes: false
          makeLatest: true
